### ISSUE TITLE
Alternative method to fit geometric series

### ISSUE THREAD

**Issue by piklprado** [piLaboratory/sads#10]
Check if He & Tang's (2008, Acta Oecol.)  method  to fit geometric series can/should be included in fitgs.

**Comment by andrechalom** [comment]
The formula by He & Tang is very accurate for such a simple formula, at least for our datasets. For instance, it predicts k = 0.089 for `birds`, and the MLE is k=0.085. I'm including it as a starting value in the `fitgs` function, but it does not seem to improve the accuracy nor the performance of the function.
