### ISSUE TITLE
Octav code fails for fitsad with 0s

### ISSUE THREAD

**Issue by andrechalom** [piLaboratory/sads#100]
```R
> octav(fitbs(c(0, 1,1,1,1)))
Error in floor(min(log2((y)))):-1 : result would be too long a vector
```

This seem to happen because the code for `octav` only discards zeros if the x argument is numeric. Is there any reason for this?

Relevant code from octav function:
```R
  1 octav <- function(x, oct, preston=FALSE){
  2   if(is(x, "fitsad"))
  3     y <- x@data$x
  4   else if(is(x,"fitrad"))
  5     y <- x@rad.tab$abund
  6   else if(is(x,"numeric"))
  7     y <- x[x>0]
  8   if(missing(oct)){
  9     oct <- 0:(ceiling(max(log2(y)))+1)
 10     if(any(y < 1)){
 11       octlower <- floor(min(log2((y)))):-1
 12       oct <- c(octlower, oct)
 13     }
 14   }
```

**Comment by piklprado** [comment]
Can't remember any reason, but it is odd such an specific code if `y<- y[y>0]` after the if's solves the problem.

**Comment by andrechalom** [comment]
On branch "octavS4", I'm rewriting the `octav` function to be an S4 method, as `octavpred` and `radpred` are. It will have "numeric", "fitsad" and "fitrad" signatures. I'm also adapting the function to use `genoct` for generating octaves such as `octavpred` does.

Finally, I'm removing the line
```R
oct <- min(oct):max(oct)
```

This is (1) inconsistent with the handling of octaves in `octavpred` and (2) undocumented.
