### ISSUE TITLE
Update install_github on project site on GitHub

### ISSUE THREAD

**Issue by MarioJose** [piLaboratory/sads#103]
Hi all,

On GitHub [sad project site](http://pilaboratory.github.io/sads/) the command to install 'dev' branch need update in parameters of **install_github** function. The second parameter now is "username" and not "ref".
From:
```r
install_github('piLaboratory/sads', 'dev')
```
to:
```r
install_github(repo = 'piLaboratory/sads', ref= 'dev')
```
Regards!

Mario

**Comment by piklprado** [comment]
Done. Thanks.
