### ISSUE TITLE
rsad should not accept incompatible S/N

### ISSUE THREAD

**Issue by andrechalom** [piLaboratory/sads#110]
The function `rsad` has one input parameter "S", and the underlying distribution from which to sample may have a parameter S (see discussion on #16). The function should not accept a value for S that is different from the specified in the coefficients. The issue also arises when the distribution has a parameter N (ls) or J (mzsm/volkov), because the value of S may be deduced from the value of the parameters.

**Comment by piklprado** [comment]
Currently we have the following distributions that have the number of species as parameter:

- Broken-stick (dbs/drbs), parameter S
- Geometric series (dgs), parameter S
- Zipf (dzipf), parameter N
- Zipf-Mandelbrodt, parameter N

For those I think `rsad` should ignore the value given in its argument S and issue a warning that the number of species indicated by the argument of the distribution is being used instead.

**Comment by piklprado** [comment]
The distributions that have the total number of individuals as parameter are

- Log-series (dls), argument `N`
- Metacommunity zsm, (dmzsm), argument `J`
- Volkov's zsm, (dvolkov), argument `J`

For those I think `rsad` should also ignore its argument `S` and issue a warning that the expected number of species given the argument of the number of individuals is used instead. The expects values for the expected number of species E[S] are:

- for log-series $E[S] = \alpha log(1+ N/\alpha)$

**Comment by andrechalom** [comment]
For gs, mand and zipf, we have the expected number of species (S), but what we need is the expected number of individuals to be sampled. Do we have a conversion like the formulas provided above for log-series & etc?

**Comment by piklprado** [comment]
I think the expected number of individuals to be sampled from any rad distribution has to be provided by the user. But this raises another question: how to draw a negative binomial sample froma rad distribution? Sampling from rad seems far more complicated and less useful than sampling from sads. So I suggest to keep `rsad` only for sampling from sad distributions and to open a separate issue to work on a prospective `rrad` function.

**Comment by piklprado** [comment]
Seems solved for rsad. Can we close this issue and create another one for the issues concerning rrad?
