### ISSUE TITLE
rsad / rrad should accept `replace=FALSE`

### ISSUE THREAD

**Issue by andrechalom** [piLaboratory/sads#111]
The code for rrad might be easily adapted for sampling without replacement from the population. Can we do the same for rsad as well? What happens for continuous distributions?

**Comment by andrechalom** [comment]
Included a "fixed" sampling scheme in rsad, which is acomplished by "sample(..., replace=FALSE)`. The name "fixed" may be changed to something more precise, and the documentation may require a better explanation.

**Comment by andrechalom** [comment]
Running some tests on the "fixed" sampling, I have found out that the parameter estimates from `fitpoilog(rsad("lnorm", ...))` are very very close to those generated with sampling="poisson". However, there seems to be less variability in the number of species and individuals with the "fixed" scheme. Other than that, the fixed scheme is a bit slower, but provides good results for frac ~ 1, while poisson fails in this case.

Some code to generate these data

```R
mu.p <- c()
sig.p <- c()
s.p <- c()
n.p <- c()
mu.f <- c()
sig.f <- c()
s.f <- c()
n.f <- c()
for (i in 1:100) {
  cat(i, ", ")
  x <- rsad(S=1e6, frac=1e-5, sad="lnorm", coef=list(meanlog=5, sdlog=2), sampling="poisson")
  s.p[i] <- length(x)
  n.p[i] <- sum(x)
  try(y <- fitpoilog(x))
  mu.p[i] <- coef(y)[1]
  sig.p[i] <- coef(y)[2]
  x <- rsad(S=1e6, frac=1e-5, sad="lnorm", coef=list(meanlog=5, sdlog=2), sampling="fixed")
  s.f[i] <- length(x)
  n.f[i] <- sum(x)
  try(y <- fitpoilog(x))
  mu.f[i] <- coef(y)[1]
  sig.f[i] <- coef(y)[2]
}
```

**Comment by piklprado** [comment]
in commit  4cbbe5c I changed the name of the option "fixed" to "hypergeometric", following the nomenclature of Connolly (2009). It is the best known paper that makes the distinction between different simulation schemes. Also, naming all sampling schemes after statistical distributions seems more coherent to me.

**Comment by piklprado** [comment]
The "hypergeometric" option with ssize>1 is repeating the same sample:

```r
> set.seed(42)
> sln3 <-  rsad(S=100, frac=0.5, sad="lnorm", coef=list(meanlog=5, sdlog=2), sampling="hyper", ssize=10)
> sln3[sln3$specie==1,]
    sample species abundance
1        1       1     71961
101      2       1     71961
201      3       1     71961
301      4       1     71961
401      5       1     71961
501      6       1     71961
601      7       1     71961
701      8       1     71961
801      9       1     71961
901     10       1     71961
```

**Comment by piklprado** [comment]
I am changing the milestone to 0.3.0 under the general idea of improving `rsad` in this version (issue #112, scheduled for 0.3.0)

**Comment by andrechalom** [comment]
Fixed. It should be noted that in hypergeometric sampling, the samples are ordered, so the most abundant species is always species number 1:
```R
> sln <-  rsad(S=100, frac=0.5, sad="lnorm", coef=list(meanlog=5, sdlog=2), sampling="hyper", ssize=10)
> sln[sln$species==1,]
    sample species abundance
1        1       1     88322
101      2       1     88023
201      3       1     88409
301      4       1     88465
401      5       1     88485
501      6       1     88888
601      7       1     88514
701      8       1     88451
801      9       1     88371
901     10       1     88525
```
