### ISSUE TITLE
rsad interface can be more clear

### ISSUE THREAD

**Issue by andrechalom** [piLaboratory/sads#112]
The arguments for rsad need be reorganized. For example, "Pois.samp=TRUE" might be replaced by a "sampling=c('poisson', 'nbinom')" switch.

**Comment by piklprado** [comment]
Absolutely. Also, we should include an argument `coef` for the coefficients of the distribution indicated by the argument `sad`, intead of handling this through `...`

**Comment by piklprado** [comment]
See comment 111#issuecomment-167882749

**Comment by piklprado** [comment]
Now waiting check of commit  	9f1b86d
