### ISSUE TITLE
dzmsm returns probabilties for non-integers

### ISSUE THREAD

**Issue by piklprado** [piLaboratory/sads#119]
The regional metacommunity zero-sum multinomial is a discrete distribution, but the function `dzsm` currently returns values to no non-integers to

```r
> distr("mzsm")
[1] "discrete"
> dmzsm(c(1,1.1), 1000, 20)
[1] 0.2486041 0.2255743
```

So we have to make [dpq]zsm comply with the standard behavior of discrete probability functions in R, which is to return zero for non-integers

```r
> dpois(c(1,1.1), lambda=1)
[1] 0.3678794 0.0000000
Warning message:
In dpois(c(1, 1.1), lambda = 1) : non-integer x = 1.100000
```
It is already implemented for the other discrete distributions in sads.

**Comment by andrechalom** [comment]
[q] functions are not affected. pmzsm already checks for non-integer values. 

Fixed dmzsm and pushed it directly to dev branch, as the change is really minor.

Checking the code for all discrete distributions: [dp]gs, [dp]rbs, [dp]power, [dp]powbend, [dp]poilog, [dp]mand, [dp]ls, [dp]volkov and [dp]zipf all comply.
