### ISSUE TITLE
Create/plot rank-abudances with relative abundances

### ISSUE THREAD

**Issue by piklprado** [piLaboratory/sads#121]
To compare rank-abundance plots with different total number of individuals is is usual to plot relative abundances. Two options:

- To include an argument in ploting methods for `rad` objects. Pros: easy to implement, same logic already applied to `plot(octav)`. Cons: does not allow to create a `rad` or `radpred` object with relative abundances. 

- To allow rad and radpred return relative abundances instead (or additionally?). Pros:  allow users to do any other work with relative abundances. Cons: harder to implement, extensive checks of compatibility.

I can take care of this and I am inclined to the 1st alternative. But I would like to know your thoughts about that @andrechalom .  
 
Sidenote: in both cases I think we should also allow relative abundances (for `rad`) and species frequencies (`octav`) in the plot method for `fitsad` and `fitrad` classes.

**Comment by andrechalom** [comment]
I really think that the first alternative is better. The second alternative
has a lot of potential of breaking existing code for anyone who relies on
the sads package, so I'm opposed to it.

I think that this should be documented on the vignette, as it really has
potential to be useful for other researchers.

**Comment by andrechalom** [comment]
Fixed some bugs on this issue and merged
