### ISSUE TITLE
Why not use Brent's method in `fitgeom` ?

### ISSUE THREAD

**Issue by piklprado** [piLaboratory/sads#125]
The geometric distribution (not geometric series) has a single free parameter and could be fitted by Brent's method. Any reason to not do so?

**Comment by andrechalom** [comment]
Yes, there is. Brent's method needs an upper and lower bounds to initiate.
sads version 0.1 used to work with Brent's for gs, but this was removed
when we noticed that some "weird" datasets were failing because the
estimated parameter was way above our "upper" guess.

**Comment by andrechalom** [comment]
See NEWS, on 0.2.2

 + fitgeom uses default optimization method from mle2 instead of Brent's method, to avoid some overflow errors for large datasets (e.g. moths)

**Comment by piklprado** [comment]
Ok. Just for to record, an example of failing fit that is solved setting `method=Brent`. We might include something about that in the documentation.

```r

> SAD_geom<-fitgeom(x=data, method="Brent")
Error in optim(par = 5.0999898000204e-05, fn = function (p)  : 
  'lower' and 'upper' must be finite values
> SAD_geom<-fitgeom(x=data, method="Brent", lower=1/(mean(data)*10), upper=10/mean(data))
> SAD_geom
Maximum likelihood estimation
Type: discrete  species abundance distribution
Species: 51 individuals: 1000002 

Call:
mle2(minuslogl = function (prob) 
-sum(dtrunc("geom", x = x, coef = prob, trunc = trunc, log = TRUE)), 
    start = list(prob = 5.0999898000204e-05), method = "Brent", 
    data = list(x = list(28277, 14958, 1171, 92862, 36160, "etc")), 
    lower = 5.0999898000204e-06, upper = 0.00050999898000204)

Coefficients:
       prob 
5.09985e-05 

Truncation point: 0 

Log-likelihood: -555.07 

## solved with
> SAD_geom <- fitgeom(x=data, method="Brent", lower=1/(mean(data)*100), upper=100/mean(data))
```

**Comment by andrechalom** [comment]
Hmm, maybe we should investigate this further. Geom should be a very easy to fit function, as it has only one parameter and has an analytic MLE. The problem here is that the parameter is too close to zero for the default optimizator - but using `lower=1/(mean(data)*10), upper=10/mean(data)` as a guess breaks datasets such as moths (for which 10/mean(data) is larger than 1)

**Comment by piklprado** [comment]
Yes,  and the fit is 0 truncated. I can not check now but I think  the
analytic mle is for the distribution including zero, isn't it?
Em 08/06/2016 17:32, "Andre Chalom" <notifications@github.com> escreveu:

Hmm, maybe we should investigate this further. Geom should be a very easy
to fit function, as it has only one parameter and has an analytic MLE. The
problem here is that the parameter is too close to zero for the default
optimizator - but using lower=1/(mean(data)*10), upper=10/mean(data) as a
guess breaks datasets such as moths (for which 10/mean(data) is larger than
1)

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/piLaboratory/sads/issues/125#issuecomment-224718306>,
or mute the thread
<https://github.com/notifications/unsubscribe/AGBVlePQbdmF00KJbGPJoT1tloixhHBoks5qJybpgaJpZM4IwDeF>
.
