### ISSUE TITLE
Vignettes when installing from GitHub

### ISSUE THREAD

**Issue by MarioJose** [piLaboratory/sads#133]
Dears, 
vignettes is not available when installing from GitHub. 'install_github' has 'build_vignettes=FALSE'. Setting 'build_vignettes = TRUE' build vignettes only in GNU/Linux. In Windows is needed 'Rtools' package to build vignettes. Maybe is interesting cite this or a link to a built vignettes in README.md or/and in project website too.
Best regards,
Mario

**Comment by andrechalom** [comment]
Added a note to README, thanks for the input!
