### ISSUE TITLE
Using proportions instead of abundances in fitsad()

### ISSUE THREAD

**Issue by padpadpadpad** [piLaboratory/sads#134]
Hi

Think the package is great...

I have community sequencing data which I need to normalise for abundance between samples to account for sampling differences. In alpha diversity measures and other analyses you can change abundance counts into proportions.

However fitsad() needs abundances (or at least positive integers) which means the value of mu is not comparable across samples. Is there anyway for me to use fitsad() to fit on the proportions and not the abundances or do I have to write my own thing in mle2()...

Many thanks

**Comment by piklprado** [comment]
Thanks Daniel

If you want to compare samples with different sizes please take a look at  sampling theory for sads (Green & Plotkin Ecol Letters 2007, Sæther et al Journal Animal Ecol 2013). Long story short, relative abundances can do the job if you have Poisson samples of a large proportion of the total community. In this case you could use continuous distributions like (truncated) lognormal, gamma, etc. Moreover, Poisson-lognormal and Fisher Logseries are discrete distributions of abundances expected from Poisson samples taken from lognormal and gamma distributions, respectively. Both models have parameters that are not affected by sampling size (sigma in lognormal and Fisher's alpha of logseries) that you can compare even if you have count data from different sample sizes. 

Hope this helps. Please let me know if it didn't.

**Comment by andrechalom** [comment]
I'm closing the issue as it did not receive feedback for some months now. If there is something we can do, please write and we'll reopen it.
