### ISSUE TITLE
Error with AICc function

### ISSUE THREAD

**Issue by bergerjosef** [piLaboratory/sads#137]
When calling AICc() on a fitsad object, following message appears, regardless of model chosen:
> Error in nobs.default(X[[i]], ...) : no 'nobs' method is available

Of course this can be fixed manually, but isn't it possible that the AICc() function imports the nobs value from the fitsad object directly?

**Comment by andrechalom** [comment]
Hello. Can you provide us a minimal working example and the version of R, sads and bbmle packages you are currently using? The package now on CRAN is supposed to use the nobs value from the fitsad object:

```R
> library(sads)
Loading required package: bbmle
Loading required package: stats4
> help(package="sads")
  Version:            0.4.0
  Date:               2017-06-16
> fit.moth = fitsad(moths, "ls")
> AICc(fit.moth)
[1] 2177.442
```

**Comment by bergerjosef** [comment]
Hello I use the following. 

R version 3.4.1 (2017-06-30)
sads version: 0.4.0 (2017-06-16)
bbmle version: 1.0.19 (2017-04-18)
stats4 version: 3.4.1 

> library(sads)
> fit <- fitsad(moths, "ls")
> fit
> AICc(fit)

Error in nobs.default(X[[i]], ...) : no 'nobs' method is available

**Comment by andrechalom** [comment]
Hm. This is confusing. Maybe you are using the function AICc from another namespace? What happens if you explicitly use `sads::AICc(fit.moth)`?

**Comment by bergerjosef** [comment]
Then I get the same error message: Error in nobs.default(X[[i]], ...) : no 'nobs' method is available

Same for all other models I have tested.

To get it work, I have to add nobs manually as an argument:
> sads::AICc(fit.moth, nobs=240)
[1] 2177.442

**Comment by andrechalom** [comment]
This is very odd. I am unable to reproduce this bug in my environment.

Can you run these in your environment to see if we can trace the issue?

```R
> R.version
> loadedNamespaces()
> fit = fitsad(moths, "ls")
> nobs(fit)
> class(fit)
> showMethods(classes="fitsad")
```

Thanks for your time!

**Comment by andrechalom** [comment]
A temporary workaround might be setting up a custom AICc function such as
```R
> myAICc = function(x, ...) AICc(x, ..., nobs = length(x@data$x))
> myAICc(fitls(moths),fitlnorm(moths))
      AICc df
1 2177.442  1
2 2199.496  2
```

**Comment by bergerjosef** [comment]
Thank you for your help! I guess now that the problem lies in interference with the {VGAM} package which I recently installed. I will try to get rid of it and try again.


`
> R.version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          4.1                         
year           2017                        
month          06                          
day            30                          
svn rev        72865                       
language       R                           
version.string R version 3.4.1 (2017-06-30)
nickname       Single Candle   

> loadedNamespaces()
 [1] "MASS"      "poilog"    "VGAM"      "compiler"  "sads"      "graphics"  "tools"     "utils"     "grDevices" "Rcpp"     
[11] "stats"     "bbmle"     "datasets"  "GUILDS"    "splines"   "grid"      "methods"   "numDeriv"  "stats4"    "base"     
[21] "caroline"  "lattice"  

> fit = fitsad(moths, "ls")
> nobs(fit)
Error in nobs.default(fit) : no 'nobs' method is available

> class(fit)
[1] "fitsad"
attr(,"package")
[1] "sads"

> showMethods(classes="fitsad")

Function ".DollarNames":
 <not an S4 generic function>

Function "attrassign":
 <not an S4 generic function>

Function "biplot":
 <not an S4 generic function>

Function "calibrate":
 <not an S4 generic function>

Function "case.names":
 <not an S4 generic function>

Function "cdf":
 <not an S4 generic function>
Function: coef (package stats)
object="fitsad"
    (inherited from: object="mle2")


Function "Coef":
 <not an S4 generic function>
Function: coefficients (package stats)
object="fitsad"


Function "Coefficients":
 <not an S4 generic function>
Function: coerce<- (package methods)
from="fitsad", to="mle2"


Function "complete":
 <not an S4 generic function>

Function "concoef":
 <not an S4 generic function>

Function "constraints":
 <not an S4 generic function>

Function "deplot":
 <not an S4 generic function>

Function "depvar":
 <not an S4 generic function>

Function "df.residual":
 <not an S4 generic function>

Function "dfbeta":
 <not an S4 generic function>

Function "effects":
 <not an S4 generic function>

Function "endf":
 <not an S4 generic function>

Function "familyname":
 <not an S4 generic function>
Function: fitted (package stats)
object="fitsad"

Function: fitted.values (package stats)
object="fitsad"


Function "formals<-":
 <not an S4 generic function>

Function "functions":
 <not an S4 generic function>

Function "guplot":
 <not an S4 generic function>

Function "has.intercept":
 <not an S4 generic function>

Function "hatplot":
 <not an S4 generic function>

Function "hatvalues":
 <not an S4 generic function>

Function "hdeff":
 <not an S4 generic function>
Function: initialize (package methods)
.Object="fitsad"
    (inherited from: .Object="ANY")


Function "is.bell":
 <not an S4 generic function>

Function "is.buggy":
 <not an S4 generic function>

Function "is.parallel":
 <not an S4 generic function>

Function "is.zero":
 <not an S4 generic function>

Function "latvar":
 <not an S4 generic function>

Function "linkfun":
 <not an S4 generic function>
Function: logLik (package stats)
object="fitsad"
    (inherited from: object="mle2")


Function "lrp":
 <not an S4 generic function>

Function "lrtest":
 <not an S4 generic function>

Function "lv":
 <not an S4 generic function>

Function "lvplot":
 <not an S4 generic function>

Function "margeffS4VGAM":
 <not an S4 generic function>

Function "Max":
 <not an S4 generic function>

Function "meplot":
 <not an S4 generic function>

Function "model.frame":
 <not an S4 generic function>

Function "model.matrix":
 <not an S4 generic function>
Function: nobs (package stats)
object="fitsad"
    (inherited from: object="ANY")


Function "nparam":
 <not an S4 generic function>

Function "npred":
 <not an S4 generic function>

Function "nvar":
 <not an S4 generic function>
Function: octav (package sads)
x="fitsad"

Function: octavpred (package sads)
object="fitsad", sad="missing", rad="missing", coef="missing", trunc="missing", oct="ANY", S="missing", N="missing"


Function "Opt":
 <not an S4 generic function>

Function "persp":
 <not an S4 generic function>
Function: plot (package graphics)
x="fitsad", y="ANY"

Function: ppsad (package sads)
x="fitsad", sad="missing", coef="missing", trunc="missing"


Function "predictors":
 <not an S4 generic function>

Function "predictvglmS4VGAM":
 <not an S4 generic function>

Function "prompt":
 <not an S4 generic function>

Function "psint":
 <not an S4 generic function>
Function: qqsad (package sads)
x="fitsad", sad="missing", coef="missing", trunc="missing", distr="missing"


Function "QR.Q":
 <not an S4 generic function>

Function "QR.R":
 <not an S4 generic function>

Function "qtplot":
 <not an S4 generic function>
Function: radpred (package sads)
object="fitsad", sad="missing", rad="missing", coef="missing", trunc="missing", distr="missing", S="missing", N="missing"


Function "Rank":
 <not an S4 generic function>

Function "resid":
 <not an S4 generic function>
Function: residuals (package stats)
object="fitsad"


Function "responseName":
 <not an S4 generic function>

Function "rlplot":
 <not an S4 generic function>
Function: show (package methods)
object="fitsad"


Function "showsummaryvglmS4VGAM":
 <not an S4 generic function>

Function "showvgamS4VGAM":
 <not an S4 generic function>

Function "showvglmS4VGAM":
 <not an S4 generic function>
Function: summary (package base)
object="fitsad"


Function "summaryvglmS4VGAM":
 <not an S4 generic function>

Function "term.names":
 <not an S4 generic function>

Function "terms":
 <not an S4 generic function>

Function "Tol":
 <not an S4 generic function>

Function "trplot":
 <not an S4 generic function>

Function "variable.names":
 <not an S4 generic function>

Function "vplot":
 <not an S4 generic function>

Function "weights":
 <not an S4 generic function>
`

**Comment by andrechalom** [comment]
Yes, that is most probably the cause. When attaching the package VGAM, my R session shows that it "masks" sads::AICc in favor or VGAM::AICc. 

I would recommend using the library calls in the reverse order:
```R
> library(VGAM)
> library(sads)
```

**Comment by bergerjosef** [comment]
A restart without VGAM solved the problem. Thank you!
