### ISSUE TITLE
Use of "representation" is deprecated in R 3.0.0

### ISSUE THREAD

**Issue by andrechalom** [piLaboratory/sads#138]
From setClass help page,

> representation, access, version, S3methods : _All these arguments are deprecated from version 3.0.0 of R and should be avoided_.
> ‘representation’ is an argument inherited from S that included both ‘slots’ and ‘contains’, but the use of the latter two arguments is clearer and recommended.

**Comment by piklprado** [comment]
So all we should do is to transfer what's currently in representation to contains and slots, like

`setClass("fitsad", representation("mle2", sad="character", distr="character", trunc="numeric"))`

to

`setClass("fitsad", contains="mle2", slots= c(sad="character", distr="character", trunc="numeric"))`

Looks pretty straightfoward, or am I missing something more complicated here?

**Comment by andrechalom** [comment]
Yes, the fix seems to be very straightforward.
