### ISSUE TITLE
problem with L-BFGS-B when using powbend

### ISSUE THREAD

**Issue by bergerjosef** [piLaboratory/sads#144]
Trying the bended powerlaw distribution with the following code 

`abundance.vector <- c(3865,3521,2612,332,161,160,24,19,11,5,5,3,2,2,1)`
`library(sads)`
`test.powbend <- fitsad(abundance.vector, 'powbend')`
gives

> Error in optim(par = c(1.2399585236562, 3), fn = function (p)  : 
>  L-BFGS-B needs finite values of 'fn'

It seems that at some point in the optimisation, the function returns infinite values. Is there some workaround to get powbend to work?

When I try the unbended powerlaw function,
`test.power <- fitsad(abundance.vector, 'power')`
instead, this problem does not occur. 

Also, when I tested powbend with other abundance samples, the problem did not occur. 

R version 3.4.1 
sads version: 0.4.1 
bbmle version: 1.0.20

**Comment by andrechalom** [comment]
Hi! 

We have attempted to provide good guesses for the parameters as `start.values` for the optimization functions. However, this is easier in some distributions and harder in others... When running in these kind of issue, you can try providing different start.values to the optimization function. In your particular example, this will work:

```R
fitpowbend(abundance.vector, start.value=c(1.2299,5))
```

**Comment by bergerjosef** [comment]
Thank you!

**Comment by piklprado** [comment]
Hi Josef,

The gory details of optmization, as Ben Bollker use to say. You can also try different optmizers. In this case

`fitpowbend(abundance.vector, optimizer="nlminb")`

Returns exactly the same fit of André's solution.

Cheers
