### ISSUE TITLE
fitvolkov gets stuck

### ISSUE THREAD

**Issue by liachica** [piLaboratory/sads#145]
Hi all,
we're trying to use the function fitvolkov but when it runs it gets stuck. Without an error I can't debug the problem. I have the latest sads package installed and R version 3.4.2 installed.
We tried on several computers, same problem.
Below is an example code that doesn't finish running. Suggestions?

Many thanks.

`#example issue with volkov

library(sads)

data<-c(28277,14958,1171,7195,39377,4778,23065,2540,539,32960,22654,27560,46851,29212,12401,20025,3037,2310,25749,9734,13305,13432,20931,24576,8225,18082,28732,4746,6324,3794,16274,1887)

SAD_geom<-fitgeom(x=data) #works
SAD_volkov<-fitvolkov(x=data) #volkov gets stuck

plot(rad(data))
lines(radpred(SAD_geom), col=1)
lines(radpred(SAD_volkov), col=2)`

**Comment by andrechalom** [comment]
Hi! I believe the problem is that the calculations needed are extremely long. `fitvolkov` works perfectly for sads in which the most abundant species has ~2.000 individuals, but your example has species with ~20.000 individuals, so this will take a looong time. Does `fitmzsm` work?

**Comment by liachica** [comment]
Well, it runs faster. But I doubt fitmzsm's results, because it never fits any data (I've tried) even reasonably well. e.g. when compared to other models (using AIC) it always comes dead last 
Here it is on the same data I just sent
![example_fit1](https://user-images.githubusercontent.com/31885778/35281881-4d1d2abe-0054-11e8-94e6-dcdc3da95bfc.png)

**Comment by andrechalom** [comment]
This may be due to the shape of the curve, as `mzsm` fits well some abundance curves that `geom` fails to fit:
```R
> sad_geom = fitgeom(moths)
> sad_mzsm = fitmzsm(moths)
> plot(rad(moths))
> lines(radpred(sad_geom))
> lines(radpred(sad_mzsm), col=2)
```
![mzsm](https://user-images.githubusercontent.com/1994997/35282653-26b87552-003d-11e8-8de1-6417526521b7.png)

Your example probably looks a bit better with a larger y lim:
![mzsm2](https://user-images.githubusercontent.com/1994997/35283160-954d4b86-003e-11e8-9178-564542bd183b.png)

**Comment by liachica** [comment]
Ah ha! super thanks!
