### ISSUE TITLE
Can we transfer sads repo to pilaboratory?

### ISSUE THREAD

**Issue by piklprado** [piLaboratory/sads#70]
I'd like to [transfer]( https://help.github.com/articles/transferring-a-repository/ ) the official sads repo to @pilaboratory, which is the repo of our lab.  With this we would complain to the [distributed workflow](http://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows#Integration-Manager-Workflow) we are already using: all of us have full access, but we only make changes through PRs that are evaluated by other member of the team.

Guesses on if/how/when we do the transfer?

**Comment by murilomiranda** [comment]
Sure, just let me know when you transfer it (if you do).

**Comment by piklprado** [comment]
Done. Please update your remotes, if you have any.
