### ISSUE TITLE
Residuals, fitted.values, etc

### ISSUE THREAD

**Issue by andrechalom** [piLaboratory/sads#71]
The R manual from `package:stats` states that:

     All object classes which are returned by model fitting functions
     should provide a ‘coef’ method or use the default one.  (Note that
     the method is for ‘coef’ and not ‘coefficients’.)

     All object classes which are returned by model fitting functions
     should provide a ‘residuals’ method.  (Note that the method is for
     ‘residuals’ and not ‘resid’.)

However, the `fitsad` and `fitrad` classes do not implement these methods, and calling the standard methods fail with:

```R
> coefficients(fitgamma(moths))
Error: $ operator not defined for this S4 class
> fitted.values(fitgamma(moths))
Error: $ operator not defined for this S4 class
> residuals(fitgamma(moths))
Error : object of type 'closure' is not subsettable
Error in gfun(object, newdata = newdata, location = location, op = "predict") : 
  can only use predict() if formula specified
> predict(fitgamma(moths))
Error : object of type 'closure' is not subsettable
Error in gfun(object, newdata = newdata, location = location, op = "predict") : 
  can only use predict() if formula specified
```

Implementing most of these accessors should be pretty straightforward.

**Comment by piklprado** [comment]
We actually have a `coef` method, which is inherited from `bbmle::mle2` class. I wonder why the other two methods you mentioned are not implemented for that class. I think we could ask @bbolker.

**Comment by piklprado** [comment]
Still `radpred` does the job of a `predict` method and `octavpred` can be viewed as a variant of prediction methods. Do you think we should join both under an alias `predict`?

**Comment by andrechalom** [comment]
Implemented coefficients (alias for coef), fitted (wrapper for radpred) and residuals (using fitted). After some tought, I don't see any case for which we would like to have a different function for predict, so I think we can close this issue after the PR is checked and merged.
