### ISSUE TITLE
Is it possible to return the limits from plotprofmle?

### ISSUE THREAD

**Issue by andrechalom** [piLaboratory/sads#84]
Bernardo Niebuhr suggests that the code used by plotprofmle could be used to return the limits of the plausibility regions. Should we implement that? And how?

**Comment by piklprado** [comment]
Sure, this is a much-needed generic improvement for likelihood-based inference. It is a very common suggestion by my students too. I wonder why such an obvious functionality is not available in R yet. Package [ProfileLikelihood](https://cran.r-project.org/web/packages/ProfileLikelihood/ProfileLikelihood.pdf) has methods for some classes of models, but I think we can create a generic that works on objects of the class profile. What do you think to use interpolation to find the limits of the likelihood region?

**Comment by andrechalom** [comment]
Looking at ProfileLikelihood source, all it does is select `min( profile [ lik > 1/k ] )` and `max( profile [ lik > 1/k ] )`, so I don't think that's a very robust package. I think we need something that:

1. Allows for a single plausibility interval or multiple disjoint intervals
2. Is reasonably robust in cases where the likelihood profile is turbulent (some of the limits might be `Inf`)
3. Is coherent with the plotted lines from `plotprofmle`.

Probably, the right thing to do is extract the code from inside the `plotprofmle` function, use it as an autonomous function (should we name it `confint`? or else?) and call this new function inside `plotprofmle`.

**Comment by andrechalom** [comment]
OK, we already have a `confint` method, inherited from bbmle. Its results are very similar to what we get inside plotprofmle for well behaved profiles, for 95% confint vs. log(8) profmle:

```R
> confint(fitgamma(moths))
Profiling...
            2.5 %      97.5 %
shape 0.354118877 0.473317489
rate  0.004878463 0.007974777
> par(mfrow=c(1,2))
> plotprofmle(fitgamma(moths))
```  
![plotprofmle](https://cloud.githubusercontent.com/assets/1994997/10497448/5292280c-729c-11e5-88c1-2f28012ded07.png)

The trouble arises when the profile is not well behaved. In these cases, everything gets weird:

```R
profile(fitvolkov(okland)) -> trouble
plotprofmle(trouble, which=2, ratio=log(4))
```

![trouble](https://cloud.githubusercontent.com/assets/1994997/10498114/36ab50ba-72a0-11e5-9641-80f119830b6f.png)

And the number of intervals is not the only weirdness. As the profile is VERY unruly, we have some negative values in the interpolated profile. Increasing the number of interpolation segments does not help here. This 'rollercoaster' near zero happens not because the *profile* is negative, but because the spline method is not able to deal with this amount of variation without going negative.

We can try to use non-negative splines with "monoH.FC" method from `splinefun`, but I'm not sure if this will give us the desired result (monoH.FC results added in green):

![monoh](https://cloud.githubusercontent.com/assets/1994997/10499070/9f9d0894-72a4-11e5-84e8-5e3a7ab42e6b.png)

From some other quick tests, monoH.FC seems to give exact matches with profiles from the more well behaved models.

**Comment by andrechalom** [comment]
OK, now for the original issue. As I'm being unable to generate a profile in which there is more than one interval in the original profile, I'm using this cheap trick:

```R
trouble@profile[1][[1]][11,1]<-0.35
plotprofmle(trouble, ratio=.13, which=1)
``` 
![trouble](https://cloud.githubusercontent.com/assets/1994997/10500426/8fe3bdda-72ae-11e5-871d-d782ab82e764.png)

This graph was generated using code from branch `confint` (WIP) which will also be used to generate the likelihood regions (function `likelregions`?) which will output a list with N elements for N parameters, each containing a list of regions.

**Comment by andrechalom** [comment]
This is the result from `likelregions` right now. The format is not very pretty, but it does the job. Should we continue to work on this?

```R
> likelregions(trouble, ratio=0.13)
$theta
$theta[[1]]
[1] 3.620489 7.505677
$theta[[2]]
[1]  9.185759 12.073400
$m
$m[[1]]
[1] 0.01575449 0.15351399
```

**Comment by bniebuhr** [comment]
Hi hi!
Nice to see this discussion here!
@andrechalom, is there a nice solution until now?
Or: do you guys think it is reasonable to use "confint" (from bbmle) for well behaved (though not symmetric) profiles?
(wondering that before re-submitting a manuscript)

**Comment by andrechalom** [comment]
First of all, I think `confint` is perfectly reasonable, and it's what we've been using for the last few years. For comparable confidence intervals (95% for confint, ratio=2 for likelregion), the values for the interval limits are very similar in all real cases I have examined.

However, the code for `likelregions` has two advantages:
1. the interpretation of the likelihood regions does not depend on assuming that the profile is well-behaved
2. the numeric value of the likelihood region limit is exactly what you see on the plotprofmle graph, while the values for confint are just approximately the same.

I'm waiting for some output from @piklprado here before incorporating the changes to the published package, and we will also add a description of the likelregions to the package vignette, so probably this code will only be sent to CRAN next year.

**Comment by piklprado** [comment]
Working perfectly, great to have a function for likelihood intervals. I addeed a box in the vignette about the two kind of intervals, please feel free to commnet/change.

**Comment by piklprado** [comment]
Keeping this issue open to evaluate if a class for `likelregions` is feasible now.
